authorName: Marcos Yamasaki
experimentName: TimeSeriesDecompose_ONS_KNN_EMD_IMF_6_RMSE
trialConcurrency: 1
maxExecDuration: 999999h
maxTrialNum: 99999
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_knn.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: C:\Users\marko\Anaconda3\envs\venvAUTO_CPU\python.exe ../src/TimeSeriesDecompose.py -nni
  codeDir: .
  gpuNum: 0
